spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/the-foodie-express
    username: postgres
    password: postgresql

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect

    hibernate:
      ddl-auto: update

    show-sql: true
springdoc:
  swagger-ui:
    path: /swagger.html
    operations-sorter: method